### ISSUE TITLE
Questions : Manage buffer size

### ISSUE THREAD

**Issue by kishkool** [ableplayer/ableplayer#208]
Hi,

Is it possible to choose the buffering size with your player?

Thanks

**Comment by terrill** [comment]
@kishkool that's not supported by the HTML5 media API. What problem are you trying to solve? Judging by your original question (before you changed the name) it sounds like the Status Bar was displaying a prolonged "Buffering" message? If so, let me know the details (browser, operating system, steps to reproduce the problem, etc.). Also try the latest version of the player - I've fixed a lot of bugs over the last couple of weeks, and perhaps this is no longer a problem.

**Comment by joedolson** [comment]
It's still not possible to vary the buffer size in the media API, and there's no response from the reporter to follow up on a different issue, so I'm going to close this issue.

Also, it's been 10  years.
