### ISSUE TITLE
Audio description demo page has problems in Firefox when toggling audio descriptions

### ISSUE THREAD

**Issue by asquire** [ableplayer/ableplayer#344]
In Firefox 63.0, at least on this audio description demo page:
https://ableplayer.github.io/ableplayer/demos/video4.html
—after clicking on the audio descriptions button, the visual state of the descriptions icon does not change (it remains either white or grey), even though the video does switch between the modes of audio description being on or off; the closed captions icon also does not update after the audio description mode has been toggled. Also, the video stops instead of continuing where it was, and the play button does not operate at all at that point; to play the video, you need to click on the time/progress bar or press the replay button, but you can then pause with the pause button, though the icon does not change to the 'play' symbol. Another thing is that the numerical timer and the sequential highlighting of phrases in the transcript do not advance. Refreshing the page resets the player to the functionality it had before toggling the audio description (and the audio descriptions icon is properly white or gray depending on the last setting used).

**Comment by terrill** [comment]
@asquire thanks for reporting this issue. I can confirming that I'm experiencing this too. Here are a few additional details: 

- This only happens **after** a video has started playing. It behaves as expected if Description is toggled before playback. 
- This isn't unique to Firefox. I'm seeing it in IE11 and Safari (on Mac OS) as well. However, it doesn't seem to be a problem in Chrome (tested on both Mac & Windows).

**Comment by terrill** [comment]
Fixed in c2c6ddc59403f2774f1ee2a9cce79fd01bfa1193

**Comment by asquire** [comment]
Thanks for fixing this!

**Comment by asquire** [comment]
I've tested the same above-mentioned video page in Firefox 63.0.3 and Internet Explorer 11 since these issues were marked as resolved, and I'm seeing the same kinds of problems as before, except that with enough button clicking (multiple times among enable/disable descriptions, play/pause, and restart), the issues at least partially resolve themselves—the player is finally able to alternate between the audio described version and the non-described version. Therefore, the bugs have not been fully eliminated. And yes, this problem occurs specifically when toggling audio descriptions after the video has been started.

**Comment by asquire** [comment]
Well, for some reason, the problem stopped occurring in Internet Explorer since retesting just a few minutes earlier, but the problem persists in Firefox.
