### ISSUE TITLE
Large Play Button and H1 throwing accessibility errors

### ISSUE THREAD

**Issue by CrystalZenyth** [ableplayer/ableplayer#505]
H1 Media Player is inserted as a second H1 in our pages. Pages are only allowed to have one H1. Need to change to an H2 or add attribute aria-level="2", when I tried with JavaScript the whole player broke.

Button is throwing error as an empty button. I would like to remove aria-hidden="true" and tabindex="-1" attributes and add an aria-label="Play" tried with JavaScript and the whole player broke.

**Comment by CrystalZenyth** [comment]
H1 Media Player is inserted as a second H1 in our pages. Pages are only allowed to have one H1. Need to change to an H2 or add attribute aria-level="2", when I tried with JavaScript the whole player broke.

Button is throwing error as an empty button. I would like to remove aria-hidden="true" and tabindex="-1" attributes and add an aria-label="Play" tried with JavaScript and the whole player broke.

**Comment by terrill** [comment]
@CrystalZenyth Able Player attempts to automatically assign itself a heading at the next level within the page hierarchy.  Sometimes it fails though, in which case you can override that and force it to use `<h2>` with **data-heading-level="2"** 

Here's what the README file says about that attribute: 

> **data-heading-level** - optional; Able Player injects an off-screen HTML heading "Media Player" (or localized equivalent) at the top of the player so screen reader users can easily find the player. It automatically assigns a heading level that is one level deeper than the closest parent heading. This attribute can be used to manually set the heading level, rather than relying on Able Player to assign it automatically. Valid values are 1 through 6. A value of 0 is also supported, and instructs Able Player to not inject a heading at all. The latter should be used only if the web page already includes a heading immediately prior to the media player.

The issues with the large play button have been fixed on the [develop](https://github.com/ableplayer/ableplayer/tree/develop) branch.

**Comment by CrystalZenyth** [comment]
I downloaded and replaced our build folder and the same Play button issue persists. https://i.imgur.com/XlBIdWX.png This button needs an accessible name.

**Comment by terrill** [comment]
@CrystalZenyth did you download from the [develop](https://github.com/ableplayer/ableplayer/tree/develop) branch? 

Here's the button code in the latest version: 
`<button class="able-big-play-button" aria-hidden="false" aria-label="Play" tabindex="0" style="width: 480px; height: 366.5px;"></button>`

**Comment by CrystalZenyth** [comment]
@terrill I replaced the build folder and the error persists. Which folder is the fixed button code located in? So I will know exactly what to replace...

**Comment by terrill** [comment]
@CrystalZenyth it's in the build folder. If you peek inside [build/ableplayer.min.js](https://github.com/ableplayer/ableplayer/blob/develop/build/ableplayer.min.js) you'll see the version number at the top of the file - should be V4.4.27.

**Comment by CrystalZenyth** [comment]
@terrill I replaced the build folder and double check the version number. https://i.imgur.com/PimdByg.png I flushed cache and still the error persists.

**Comment by terrill** [comment]
@CrystalZenyth on your live site you're loading AblePlayer/build/ableplayer.js and that file appears to be an older version. Be sure to replace that as well, or change your `<script>` element to load the minimized version AblePlayer/build/ableplayer.min.js.

**Comment by CrystalZenyth** [comment]
https://www.loom.com/share/41a7b2aa407648f69529c0c6045a9441

**Comment by terrill** [comment]
@CrystalZenyth the missing label on the fullscreen button has been fixed in 0eaf3cf6af4bcada6d45e27d9aa37768cc8953f8

As for the video size problem, that's a weird one. Any possibility of setting that up on a dev server?  We've made some changes to the sizing algorithm, but have tested a wide variety of combinations (see the new [Able Player Width Tests](https://github.com/ableplayer/ableplayer/blob/develop/demos/other-width.html) demo) and haven't seen that.
